# Generated by Django 4.2.11 on 2024-03-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slides/')),
                ('description', models.TextField()),
            ],
        ),
    ]
